version: "3"

services:
  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 8080 
      DB_CONN: postgresql://postgres:password@postgres:5432/mydb
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    restart: unless-stopped

